version: 2

updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      test-packages:
        patterns:
          - "FluentAssertions"
          - "Microsoft.NET.Test.Sdk"
          - "xunit"
          - "xunit.runner.visualstudio"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
